application: yacc-backend
version: 0.1.1
runtime: java
#api_version: 1
threadsafe: true
static_files: #
    - include: /test/**.json

handlers:
    - url: /update-currency-data
      login: admin
      servlet: com.omricat.yacc.backend.servlets.DownloadLatestCurrenciesServlet
      name: cronjob downloader for latest currencies

    - url: /latest
      servlet: com.omricat.yacc.backend.servlets.LatestServlet
      name: returns the most recent data from the data store

    - url: /update-names
      servlet: com.omricat.yacc.backend.servlets.CurrencyNamesServlet
      name: downloads, stores and returns names of currencies

system_properties:
    file.encoding: UTF-8
    DEFAULT_ENCODING: UTF-8

inbound_services:
- warmup
