application: yacc-backend
version: 0-1-test
runtime: java
#api_version: 1
threadsafe: true
static_files: #
    - include: /test/**.json

handlers:
    - url: /get-latest-currencies
      login: admin
      servlet: com.omricat.yacc.backend.servlets.DownloadServlet
      name: cronjob downloader for latest currencies
